## 1. Basic Math DeepLearning

In [7]:
import numpy as np
import pandas as pd

In [8]:
class ModelNeuralNetwork:
    def __init__(self, X_feature: np.ndarray,task_type: str = "regression",num_classes: int = None,N_neuron: int = None,):
        self.X_feature = self._prepare_input_feature(X_feature)
        self.n_features = self.X_feature.shape[1]
        self.task_type = task_type.lower()
        self.N_neuron = self._determine_num_neurons( N_neuron, num_classes)
        self.weight_neuron = None
        self.bias_neuron = None

    def _prepare_input_feature(self, X_feature: np.ndarray) -> np.ndarray:
        """Memastikan X_feature selalu berbentuk matriks 2D (n_samples, n_features)."""
        if X_feature.ndim == 1:
            return X_feature.reshape(1, -1)
        return X_feature

    def _determine_num_neurons(self, N_neuron: int, num_classes: int) -> int:
        """Menentukan jumlah neuron output berdasarkan parameter atau task_type."""
        if N_neuron is not None:
            return N_neuron
        if self.task_type == "binary":
            return 1
        elif self.task_type == "multiclass":
            if num_classes is None:
                raise ValueError("Parameter 'num_classes' wajib diisi untuk task_type 'multiclass'!")
            return num_classes
        elif self.task_type == "regression":
            return 1
        else:
            raise ValueError(f"task_type '{self.task_type}' tidak dikenal. ""Pilih: 'regression', 'binary', atau 'multiclass'.")
    
    def create_weight_neuron(self, seed: int = None):
        """Inisialisasi bobot dan bias secara acak."""
        if seed is not None:
            np.random.seed(seed)
        self.weight_neuron = np.random.uniform(0.0, 1.0, size=(self.n_features, self.N_neuron))
        self.bias_neuron = np.random.uniform(0.0, 1.0, size=(1, self.N_neuron))
        return self.weight_neuron, self.bias_neuron

    def transform_linear_function(self):
        """Menghitung Z = X @ W + b (Transformasi Linier)."""
        if self.weight_neuron is None or self.bias_neuron is None:
            self.create_weight_neuron()
        z = np.dot(self.X_feature, self.weight_neuron) + self.bias_neuron
        return z

    def predict(self, method: str = None):
        """Menghasilkan prediksi akhir berdasarkan tugas (Klasifikasi/Regresi) atau metode aktivasi kustom."""
        z = self.transform_linear_function()
        if method is None:
            if self.task_type == "regression":
                method = "linear"
            elif self.task_type == "binary":
                method = "sigmoid"
            elif self.task_type == "multiclass":
                method = "softmax"

        method_clean = method.lower()
        if method_clean in ["linear", "identity"]:
            return z

        elif method_clean == "sigmoid":
            return 1 / (1 + np.exp(-np.clip(z, -500, 500)))
        elif method_clean == "softmax":
            exp_z = np.exp(z - np.max(z, axis=-1, keepdims=True))
            return exp_z / np.sum(exp_z, axis=-1, keepdims=True)
        elif method_clean == "relu":
            return np.maximum(0, z)
        elif method_clean == "tanh":
            return np.tanh(z)
        else:
            raise ValueError( f"Metode aktivasi '{method}' tidak dikenali. ")


In [ ]:
X_data = np.array([[1.5, 2.0, 0.5], [0.1, 0.4, 0.9], [2.1, 1.1, 3.0], [0.8, 1.2, 0.2],[0.1, 0.4, 0.9]])

print("--- 1. KASUS REGRESI ---")
model_regresi = ModelNeuralNetwork(X_feature=X_data, task_type="regression")
output_regresi = model_regresi.predict()
print("Output Shape Regresi:", output_regresi.shape)
print("Hasil Prediksi Regresi:\n", output_regresi)


print("\n--- 2. KASUS KLASIFIKASI BINER ---")
model_biner = ModelNeuralNetwork(X_feature=X_data, task_type="binary")
output_biner = model_biner.predict()
print("Output Shape Biner:", output_biner.shape)
print("Hasil Prediksi Probabilitas Biner:\n", output_biner)


print("\n--- 3. KASUS KLASIFIKASI MULTIKELAS (Misal: 3 Kelas) ---")
model_multikelas = ModelNeuralNetwork( X_feature=X_data, task_type="multiclass", num_classes=3)
output_multikelas = model_multikelas.predict()
print("Output Shape Multikelas:", output_multikelas.shape)
print("Hasil Prediksi Probabilitas Multikelas:\n", output_multikelas)

--- 1. KASUS REGRESI ---
Output Shape Regresi: (5, 1)
Hasil Prediksi Regresi:
 [[1.35937928]
 [0.82281967]
 [2.91666364]
 [0.79480853]
 [0.82281967]]

--- 2. KASUS KLASIFIKASI BINER ---
Output Shape Biner: (5, 1)
Hasil Prediksi Probabilitas Biner:
 [[0.91422825]
 [0.63190503]
 [0.92354395]
 [0.79880527]
 [0.63190503]]

--- 3. KASUS KLASIFIKASI MULTIKELAS (Misal: 3 Kelas) ---
Output Shape Multikelas: (5, 3)
Hasil Prediksi Probabilitas Multikelas:
 [[0.35670577 0.51102403 0.1322702 ]
 [0.33530612 0.41314819 0.25154569]
 [0.69074173 0.24697711 0.06228117]
 [0.30339511 0.49929248 0.19731241]
 [0.33530612 0.41314819 0.25154569]]
