In [1]:
import torch
import numpy as np

## 1. Menginisialisasi Tensor

In [3]:
data = [[1, 2],[3, 4],[2,8]]
np_array = np.array(data)

x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4],
        [2, 8]])

In [4]:
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4],
        [2, 8]])

In [5]:
#pakai variabel x_np
x_ones_ts = torch.ones_like(x_np)
x_rand_ts = torch.rand_like(x_np, dtype=torch.float)

print(f"Ones Tensor: \n {x_ones_ts} \n")
print(f"Random Tensor: \n {x_rand_ts} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7688, 0.0899],
        [0.2628, 0.0651],
        [0.1724, 0.4853]]) 



In [6]:
shape = (3,5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1787, 0.4848, 0.4755, 0.6527, 0.8084],
        [0.1884, 0.1737, 0.0356, 0.5453, 0.1729],
        [0.2456, 0.5809, 0.4079, 0.7992, 0.1700]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
## 2.Atribut sebuah Tensor

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
