In [2]:
import numpy as np

### Membuat Array Numpy

In [4]:
arr = np.array([1,2,3])
print(arr)

arr = np.array([3,5,2,7])
print(arr)

arr = np.array([9,2,4,3])
print(arr)

[1 2 3]
[3 5 2 7]
[9 2 4 3]


### Mengakses Indeks Array

In [14]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

arr2 =arr[:2,::2]
print(f"2 baris pertama dan kolom berselanh-seling (0,2):\n {arr2}")

arr3 = arr[[1, 1, 0, 3], 
            [3, 2, 1, 0]]
print(f"\nElemen pada indeks (1,3),(1,2),(0,1),(3,0): {arr3}")

2 baris pertama dan kolom berselanh-seling (0,2):
 [[-1.  0.]
 [ 4.  6.]]

Elemen pada indeks (1,3),(1,2),(0,1),(3,0): [0. 6. 2. 3.]


### Operasi Array Dasar

In [21]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[4,5],
              [2,1]])

print(f"Menambah 1 ke setiap element A:\n {a + 1}")
print(f"\n Mengurangi 2 dari setia elemen B:\n {(b-2)}")
print(f"\n Jumlah semua elemen array:\n {a.sum()}")
print(f"\nJumlah array:\n {a+b}")

Menambah 1 ke setiap element A:
 [[2 3]
 [4 5]]

 Mengurangi 2 dari setia elemen B:
 [[ 2  3]
 [ 0 -1]]

 Jumlah semua elemen array:
 10

Jumlah array:
 [[5 7]
 [5 5]]


### Membangun Objek Tipe Data

In [33]:
x = np.array([1,2])
print(f"{x} bertipe data: {x.dtype}")

x = np.array([0.1,0.2])
print(f"{x} bertipe data: {x.dtype}")

x = np.array([1, 2], dtype = np.int64) 
print(f"{x} bertipe data: {x.dtype}")

[1 2] bertipe data: int64
[0.1 0.2] bertipe data: float64
[1 2] bertipe data: int64


### Operasi Matematika pada Tipe Data array


In [39]:
arr1 = np.array([[4,7],
                 [2,6]])

arr2 = np.array([[3,6],
                 [2,8]])

sum = np.add(arr1,arr2)
print(f"function add:\n {sum}")

sum1 = np.sum(arr1)
print(f"function sum: {sum1}")

sqrt = np.sqrt(arr1)
print(f"function sqrt:\n {sqrt}")

function add:
 [[ 7 13]
 [ 4 14]]
function sum: 19
function sqrt:
 [[2.         2.64575131]
 [1.41421356 2.44948974]]
